modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Mrbysco/SpitItOut"
license="MIT"
[[mods]]
modId="spititout"
version="${file.jarVersion}"
displayName="Spit It Out"
displayURL="https://github.com/criscky/SpitItOut/issues"
authors="Criscky, Mrbysco, ShyNieke"
description='''
Stop swallowing the exception and spit it out!
'''